[package]
name = "scriptwriter"
version = "0.1.0"
description = "A small writing application for one screenplay"
authors = ["Scriptwriter"]
license = "0BSD"
edition = "2021"

[lib]
name = "scriptwriter_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
